version: '3.7'

services:

  mongodb:
    image: mongo:4.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
     - ./mongodb/.env
    volumes:
     #- ./mongodb/database/data:/data/db
     - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error.log
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mongodb
      - app

  app:
    container_name: app
    volumes: 
      - ./app/:/app
    build: .
    depends_on:
      - mongodb
    env_file:
      - ./app/.env
